#!/bin/bash

# List of dataset folders
folders=(
ATLAS_TTBAR_13P6TEV_TOT_X-SEC
ATLAS_TTBAR_13TEV_HADR_DIF_MTTBAR
ATLAS_TTBAR_13TEV_HADR_DIF_MTTBAR-YTTBAR
ATLAS_TTBAR_13TEV_HADR_DIF_YTTBAR
ATLAS_TTBAR_13TEV_LJ_DIF_MTTBAR
ATLAS_TTBAR_13TEV_LJ_DIF_MTTBAR-PTT
ATLAS_TTBAR_13TEV_LJ_DIF_PTT
ATLAS_TTBAR_13TEV_LJ_DIF_PTT-YT
ATLAS_TTBAR_13TEV_LJ_DIF_YT
ATLAS_TTBAR_13TEV_LJ_DIF_YTTBAR
ATLAS_TTBAR_13TEV_TOT_X-SEC
ATLAS_TTBAR_5TEV_TOT_X-SEC
ATLAS_TTBAR_7TEV_TOT_X-SEC
ATLAS_TTBAR_8TEV_2L_DIF_MTTBAR
ATLAS_TTBAR_8TEV_2L_DIF_YTTBAR
ATLAS_TTBAR_8TEV_LJ_DIF_MTTBAR
ATLAS_TTBAR_8TEV_LJ_DIF_PTT
ATLAS_TTBAR_8TEV_LJ_DIF_YT
ATLAS_TTBAR_8TEV_LJ_DIF_YTTBAR
ATLAS_TTBAR_8TEV_TOT_X-SEC
CMS_TTBAR_13TEV_2L_138FB-1_DIF_MTTBAR
CMS_TTBAR_13TEV_2L_138FB-1_DIF_MTTBAR-YTTBAR
CMS_TTBAR_13TEV_2L_138FB-1_DIF_PTT
CMS_TTBAR_13TEV_2L_138FB-1_DIF_YT
CMS_TTBAR_13TEV_2L_DIF_MTTBAR
CMS_TTBAR_13TEV_2L_DIF_PTT
CMS_TTBAR_13TEV_2L_DIF_YT
CMS_TTBAR_13TEV_2L_DIF_YTTBAR
CMS_TTBAR_13TEV_LJ_DIF_MTTBAR
CMS_TTBAR_13TEV_LJ_DIF_MTTBAR-YTTBAR
CMS_TTBAR_13TEV_LJ_DIF_PTT
CMS_TTBAR_13TEV_LJ_DIF_YT
CMS_TTBAR_13TEV_LJ_DIF_YTTBAR
CMS_TTBAR_8TEV_2L_DIF_MTTBAR-YT
CMS_TTBAR_8TEV_2L_DIF_MTTBAR-YTTBAR
CMS_TTBAR_8TEV_2L_DIF_PTT-YT
)

# Save starting directory
BASE_DIR=$(pwd)

for dir in "${folders[@]}"; do
    if [ -d "$dir" ]; then
        echo "Running in $dir"

        cd "$dir" || continue

        if [ -x "run.sh" ]; then
            ./run.sh
        elif [ -f "run.sh" ]; then
            bash run.sh
        else
            echo "  run.sh not found in $dir"
        fi

        cd "$BASE_DIR" || exit
    else
        echo "Directory $dir does not exist"
    fi
done

echo "All done."
