#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Zero-dependency bootstrap script
"""
import os
import pathlib
import site
import subprocess
import sys

here = pathlib.Path(".").parent.absolute()


def update_path():
    """
    Since in some environments the User Scripts Directory (PEP-370) is not part
    of the path, let's include it to make user to be able to run `poetry`.

    (for `pre-commit` the user will have to do on its own, since it's not run by
    this script)
    """
    scripts_base_dir = (
        site.getuserbase() + "/bin"
        if not sys.platform.startswith("win")
        else r"\Scripts"
    )
    os.environ["PATH"] += os.pathsep + str(scripts_base_dir)


if __name__ == "__main__":
    update_path()
    subprocess.run("poetry run rr".split() + sys.argv[1:])
