[paths]
# paths relative to the location of this file
runcards = "nnpdf31_proc"
results = "results"
# theories = "theories"
# prefix = ".prefix"
# bin = ".prefix/bin"
# lib = ".prefix/lib"
# mg5amc = ".prefix/mg5amc"
# pineappl = ".prefix/pineappl"
# cargo = ".prefix/cargo"
# lhapdf = ".prefix/lhapdf"
# lhapdf_data_alternative = ".prefix/share/LHAPDF"

[commands]
# mg5 =  ".prefix/mg5amc/bin/mg5_aMC"
# vrap = ".prefix/bin/ "Vrap"
# pineappl = ".prefix/bin/pineappl"
