/********************************************************************
* TFileVectorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFileVectorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFileVectorDict();
extern void G__cpp_setup_inheritanceTFileVectorDict();
extern void G__cpp_setup_typetableTFileVectorDict();
extern void G__cpp_setup_memvarTFileVectorDict();
extern void G__cpp_setup_globalTFileVectorDict();
extern void G__cpp_setup_memfuncTFileVectorDict();
extern void G__cpp_setup_funcTFileVectorDict();
extern void G__set_cpp_environmentTFileVectorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TFileVector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFileVectorDictLN_TClass;
extern G__linked_taginfo G__TFileVectorDictLN_TBuffer;
extern G__linked_taginfo G__TFileVectorDictLN_TMemberInspector;
extern G__linked_taginfo G__TFileVectorDictLN_TObject;
extern G__linked_taginfo G__TFileVectorDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TFileVectorDictLN_string;
extern G__linked_taginfo G__TFileVectorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFileVectorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileVectorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFileVectorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileVectorDictLN_TObjString;
extern G__linked_taginfo G__TFileVectorDictLN_TFileVector;
extern G__linked_taginfo G__TFileVectorDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__TFileVectorDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
